# Generated by Django 2.2.4 on 2019-08-22 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 5, 14, 45, 326484, tzinfo=utc), verbose_name='fecha de publicacion'),
        ),
    ]
